- .env-non-dev
- app.sh
- docker-compose.yml
- src/users/routers.py
- tests/conftest.py
- tests/test_auth.py
- tests/test_user.py
> add tests on get by email,  del by email

- Rabbit mg diagram.drawio
add diagram with database models
> Add DB diagram

- src/frontend/static/css/authorization.css
подправил расположение формы авторизации
> css auth update

- docker-compose.yml
- src/conf.d/app.conf
> add nginx settings server with proxy to backend

- logger/logger.py
- src/frontend/static/js/aurhorization.js
- src/frontend/templates/getusers.html
- src/frontend/templates/registration.html
- src/pages/routers.py
add page get users with out all registered users
> Add get users

- .gitignore
- env-example
- src/config.py
- src/frontend/templates/getusers.html
- src/main.py
- src/pages/routers.py
add route for get current user(get users)
> Get current user

- src/frontend/static/css/getusers.css
- src/frontend/static/css/registration.css
- src/frontend/templates/getusers.html
- src/frontend/templates/grid.html
добавил чекбоксы
поменял структуру на грид
> update getusers CSS

- src/frontend/templates/getusers.html
так как все изменения на сервер отправляются кнопкой "сохранить", то тип кнопок классов будет баттон, потому что такой тип не имеет преднастроек и не перезагружает страницу
> button type change

- src/frontend/static/css/base.css
- src/frontend/static/css/getusers.css
- src/frontend/templates/base.html
поработал над замечанием и раскидал свойства base и getUsers
> debug base SCC

- src/frontend/static/css/login.css
- src/frontend/templates/login.html
заменил забыли пароль на ссылку на стр регистрации
поправил стили ввиду новых знаний в css
> add reg anchor to login page

- src/frontend/static/css/base.css
- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
закомментировал блоки кода связанные с кнопкой сохранить изменения
> button SAVE

- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
Заменил переключатели-ползунки
проблема с ползунком открывающем классы осталась
> new switches

- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
Переключатель открывающий блок классов заработал
внёс небольшое изменение в жс файл (чтобы ползунок переполз на одну линию с "подписаться")
добавил изменения в css (псевдоклассы)
> switch fix

- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
получилось сделать запрос который меняет статус подписки
НЕ получилось сделать чтобы чекбокс принимал значение статуса подписки
> patch request of check-boxes

- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
добавил блоки кода, которые отправляют работающие патч-запросы на изменение статуса подписки на:
-проценты
-оффлайн
пока это манки код - 3 идентичных блока кода с разницей нескольких переменных, по возможности попытаюсь сделать одну общую функцию.
> add Patch requests from ch-b

- src/frontend/static/css/getusers.css
- src/frontend/templates/base.html
- src/frontend/templates/getusers.html
добавил дивы с инфой по веткам
> add info-block

- src/frontend/static/css/base.css
- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
сделал заготовку всплывающего окна, которое будет спрашивать уверен ты или нет
> made modal window 

- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
Обновил внешний вид модального окна.
> RMG-51-2 modal window update styles

- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
Починил кнопку скрытия/раскрытия кружков с классами
> classes hide radio button

- src/frontend/static/css/getusers.css
- src/frontend/static/js/getusers.js
- src/frontend/templates/getusers.html
Появилась подписка на мировой рекорд, и все связанные с этим изменения в соответствующих файлах
> add WR title
